#!/bin/bash

terraform_dir=$(dirname $0)

if [ -z "${TERRAFORM_BIN}" ] ; then
    terraform_bin=$(type -p tofu || type -p terraform)
else
    terraform_bin=${TERRAFORM_BIN}
fi

if [ -z "$terraform_bin" ]; then
    echo "Could not find terraform binary in PATH.  Exiting."
    exit 1
fi
terraform="$terraform_bin -chdir=$terraform_dir"

set -e
$terraform init -upgrade
$terraform apply -target=null_resource.backend -auto-approve -compact-warnings -concise $*
$terraform apply -target=null_resource.clusters -auto-approve -compact-warnings -concise $*
$terraform init -upgrade
$terraform apply $*

