worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen 8080 default_server;
        server_name _;
        root          /usr/share/nginx/html;

        add_header Content-Security-Policy "frame-ancestors 'self'; frame-src 'self'" always;

        location = /ready {
            return 200 'no content';
        }

        location /api/ {
            index  index.html;
            try_files $uri $uri/ =404;
        }

        location = /api {
            return 301 /api/;
        }

        location /admin/ {
            index  index.html;
            try_files $uri $uri/ =404;
        }

        location = /admin {
            return 301 /admin/;
        }

        location = / {
            return 301 /admin/;
        }

        location /openidm {
            proxy_pass http://$host/openidm;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
