{{- if and .Values.ds_cts.enabled (eq .Values.ds_cts.kind "DirectoryService") }}
apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryService
metadata:
  name: ds-cts
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.ds_cts.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.ds_cts.replicaCount }}
  podTemplate:
    image: "{{ .Values.ds_cts.image.repository }}:{{ .Values.ds_cts.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.ds_cts.image.pullPolicy }}
    resources:
      {{- toYaml .Values.ds_cts.resources | nindent 6 }}
    secrets:
      masterSecretName: ds-master-keypair
      sslSecretName: ds-ssl-keypair
      truststoreSecretName: ds-ssl-keypair
    {{- with .Values.ds_cts.volumeClaimSpec }}
    volumeClaimSpec:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    volumeSnapshotClassName: ds-snapshot-class
    serviceAccountName: {{ include "identity-platform.serviceAccountName" . }}
  snapshots:
    enabled: false
    periodMinutes: 10
    snapshotsRetained: 3
  passwords:
    uid=admin:
      secretName: ds-passwords
      key: dirmanager.pw
    uid=monitor:
      secretName: ds-passwords
      key: monitor.pw
    uid=openam_cts,ou=admins,ou=famrecords,ou=openam-session,ou=tokens:
      secretName: ds-env-secrets
      key: AM_STORES_CTS_PASSWORD
{{- end }}
