{{- if and .Values.ds_idrepo.enabled (eq .Values.ds_idrepo.kind "DirectoryService") }}
apiVersion: directory.forgerock.io/v1alpha1
kind: DirectoryService
metadata:
  name: ds-idrepo
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.ds_idrepo.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.ds_idrepo.replicaCount }}
  podTemplate:
    image: "{{ .Values.ds_idrepo.image.repository }}:{{ .Values.ds_idrepo.image.tag | default .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.ds_idrepo.image.pullPolicy }}
    resources:
      {{- toYaml .Values.ds_idrepo.resources | nindent 6 }}
    secrets:
      masterSecretName: ds-master-keypair
      sslSecretName: ds-ssl-keypair
      truststoreSecretName: ds-ssl-keypair
    {{- with .Values.ds_idrepo.volumeClaimSpec }}
    volumeClaimSpec:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    volumeSnapshotClassName: ds-snapshot-class
    serviceAccountName: {{ include "identity-platform.serviceAccountName" . }}
  snapshots:
    enabled: false
    periodMinutes: 10
    snapshotsRetained: 3
  passwords:
    uid=admin:
      secretName: ds-passwords
      key: dirmanager.pw
    uid=monitor:
      secretName: ds-passwords
      key: monitor.pw
    uid=openam_cts,ou=admins,ou=famrecords,ou=openam-session,ou=tokens:
      secretName: ds-env-secrets
      key: AM_STORES_CTS_PASSWORD
    uid=am-identity-bind-account,ou=admins,ou=identities:
      secretName: ds-env-secrets
      key: AM_STORES_USER_PASSWORD
    uid=am-config,ou=admins,ou=am-config:
      secretName: ds-env-secrets
      key: AM_STORES_APPLICATION_PASSWORD
{{- end }}
