{{- if and .Values.ds_snapshot.rbacCreate (or .Values.ds_idrepo.snapshot.enabled .Values.ds_cts.snapshot.enabled) (not (lookup "v1" "ServiceAccount" .Release.Namespace .Values.ds_snapshot.serviceAccountName).metadata) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ds_snapshot.serviceAccountName }}
{{- end }}
