{{- if and .Values.ds_snapshot.rbacCreate (or .Values.ds_idrepo.snapshot.enabled .Values.ds_cts.snapshot.enabled) -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.ds_snapshot.serviceAccountName }}
{{- end }}
