apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: am
  labels:
    app: am
    app.kubernetes.io/component: am
    app.kubernetes.io/instance: am
    app.kubernetes.io/name: am
    app.kubernetes.io/part-of: forgerock
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    port: 8080
    requestPath: /am/json/health/live
  timeoutSec: 5
  connectionDraining:
    drainingTimeoutSec: 5
  sessionAffinity:
    affinityType: GENERATED_COOKIE
    affinityCookieTtlSec: 300
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: idm
  labels:
    app: idm
    app.kubernetes.io/component: idm
    app.kubernetes.io/instance: idm
    app.kubernetes.io/name: idm
    app.kubernetes.io/part-of: forgerock
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    port: 8080
    requestPath: /openidm/info/ping
  timeoutSec: 5
  connectionDraining:
    drainingTimeoutSec: 5
  sessionAffinity:
    affinityType: GENERATED_COOKIE
    affinityCookieTtlSec: 300
---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: admin-ui
  labels:
    app: admin-ui
spec:
  healthCheck:
    checkIntervalSec: 5
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 1
    type: HTTP
    port: 8080
    requestPath: /
  timeoutSec: 5
  connectionDraining:
    drainingTimeoutSec: 5
  sessionAffinity:
    affinityType: GENERATED_COOKIE
    affinityCookieTtlSec: 300